version: "3.8"

services:
  mission_dispatch:
    image: nvcr.io/nvidia/isaac/mission-dispatch:3.2.0
    ports:
      - "5000:5000"
    depends_on:
      - mission_database

  mission_database:
    image: nvcr.io/nvidia/isaac/mission-database:3.2.0
    ports:
      - "5432:5432"
    volumes:
      - mission_db_data:/var/lib/postgresql/data

  mission_simulator:
    image: nvcr.io/nvidia/isaac/mission-simulator:3.2.0
    ports:
      - "3000:3000"

volumes:
  mission_db_data:
