---
- name: Setup Docker environment
  hosts: localhost
  become: yes
  tasks:
# Add Docker's official GPG key:
    - name: Keyring directory
      command: apt update

    - name: Install required packages
      apt:
        name:
          - ca-certificates
          - curl
        state: present

    - name: Keyring directory
      command: install -m 0755 -d /etc/apt/keyrings

    - name: Download Docker GPG key
      command: curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc

    - name: Chmod Docker GPG key
      command: chmod a+r /etc/apt/keyrings/docker.asc

    - name: Add the repository to Apt sources
      shell: |
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
        $(. /etc/os-release && echo \"$VERSION_CODENAME\") stable" | \
        tee /etc/apt/sources.list.d/docker.list > /dev/null
      
    
# Install Docker   
    - name: Install Docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: latest
        update_cache: yes

    - name: Ensure Docker service is started
      service:
        name: docker
        state: started
        enabled: yes

    - name: Start Docker Compose services
      command: docker compose -f /home/vagrant/docker-compose.yml up -d
